"""init

Revision ID: 559420d0a963
Revises: 
Create Date: 2023-05-25 15:15:20.188196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559420d0a963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_id'), 'times', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('row_wpm', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_accuracy'), 'lessons', ['accuracy'], unique=False)
    op.create_index(op.f('ix_lessons_consistency'), 'lessons', ['consistency'], unique=False)
    op.create_index(op.f('ix_lessons_cpm'), 'lessons', ['cpm'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_row_wpm'), 'lessons', ['row_wpm'], unique=False)
    op.create_index(op.f('ix_lessons_wpm'), 'lessons', ['wpm'], unique=False)
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('row_wpm', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_accuracy'), 'trainings', ['accuracy'], unique=False)
    op.create_index(op.f('ix_trainings_consistency'), 'trainings', ['consistency'], unique=False)
    op.create_index(op.f('ix_trainings_cpm'), 'trainings', ['cpm'], unique=False)
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=False)
    op.create_index(op.f('ix_trainings_row_wpm'), 'trainings', ['row_wpm'], unique=False)
    op.create_index(op.f('ix_trainings_wpm'), 'trainings', ['wpm'], unique=False)
    op.create_table('profile_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('seconds_spent', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_lesson')
    op.drop_index(op.f('ix_trainings_wpm'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_row_wpm'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_cpm'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_consistency'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_accuracy'), table_name='trainings')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_lessons_wpm'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_row_wpm'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_cpm'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_consistency'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_accuracy'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_times_id'), table_name='times')
    op.drop_table('times')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
