"""active-done

Revision ID: 94dad579e146
Revises: 547a75a9770e
Create Date: 2023-05-25 16:37:55.023874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dad579e146'
down_revision = '547a75a9770e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
