"""Initial migration

Revision ID: ef5d5ec66ca5
Revises: f08753ad690f
Create Date: 2023-05-24 22:35:21.818864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5d5ec66ca5'
down_revision = 'f08753ad690f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_lesson',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'lesson_id')
    )
    op.drop_constraint('lessons_profile_id_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'seconds')
    op.drop_column('lessons', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('lessons_profile_id_fkey', 'lessons', 'profiles', ['profile_id'], ['id'])
    op.drop_table('profile_lesson')
    # ### end Alembic commands ###
